const models = require('./models')

models.Cart.sync()
models.User.sync()
models.Order.sync()
models.Product.sync()
models.ProductAttribute.sync()
models.Storage.sync()
models.ProductPrice.sync()
models.Frequency.sync()
models.FrequencyList.sync()
models.Order.sync()
models.OrderDetail.sync()
models.Trademark.sync()
models.Country.sync()
models.StorageProductList.sync()
models.ProductCategory.sync()